### ISSUE TITLE
Add LEI package

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/asn1-schema#12]

**Comment by donskov** [comment]
@microshine Any progress with the package?

https://www.etsi.org/deliver/etsi_ts/119400_119499/11941201/01.03.01_60/ts_11941201v010301p.pdf

**Comment by microshine** [comment]
I don't see any ASN.1 schemas. Just object identifiers
```
ETSISemanticsIdentifierMod { itu-t(0) identified-organization(4) etsi(0) id-certprofile(194121) id-mod(0) id-mod-semantics-identifier(0) }


DEFINITIONS EXPLICIT TAGS::=

BEGIN

-- EXPORTS All –

-- Semantics identifiers

id-etsi-qcs-semantics-identifiers OBJECT IDENTIFIER ::= { itu-t(0) identifiedorganization(4) etsi(0) id-cert-profile(194121) 1 }
-- Semantics identifier for natural person identifier
id-etsi-qcs-semanticsId-Natural OBJECT IDENTIFIER ::= { id-etsi-qcs-semanticsidentifiers 1 }

-- Semantics identifier for legal person identifier

id-etsi-qcs-SemanticsId-Legal OBJECT IDENTIFIER ::= { id-etsi-qcs-semanticsidentifiers 2 }

END 
```

**Comment by microshine** [comment]
@rmhrisk please share a link to ASN.1 module

**Comment by rmhrisk** [comment]
It seems it is not an extension just a way to encode the identifier.

**Comment by microshine** [comment]
I found that ASN.1 schema
https://www.ubisecure.com/legal-entity-identifier-lei/lei-in-digital-certificates-best-practice-definitions/

But Hancock reads that value like a UTF8 string
https://github.com/PeculiarVentures/hancock-app/blob/19eb39925b079bf77b07a239a8ec46e716564dd5/ui/packages/%40core/lib/xbrl_crypto/verify.ts#L315-L316

For some cases, it may be a part of DN
https://certificatedetails.com/1384d8e8a4c26a552b72b972f304869be982522ad99b399707af667d158265f1/idesk.gstt.nhs.uk

**Comment by microshine** [comment]
@donskov please try `@peculiar/asn1-lei@2.0.7-alpha.1`

**Comment by donskov** [comment]
@microshine Please fix oid value:
`1.3.6.1.4.1.5222266.1` => `1.3.6.1.4.1.52266.1`

**Comment by donskov** [comment]
@microshine Could we use `string` instead of `number`, because hard to understand what it is?

![image](https://user-images.githubusercontent.com/9417251/87405027-94924880-c5c7-11ea-960e-4f678fe4bb58.png)

`4` -> `sha256`
`3` -> `ecdsa`

**Comment by microshine** [comment]
Use enums

```js
HashAlgorithm[timestamp.hashAlgorithm];
```

Also this extension supports toJSON function. JSON uses string names instead of enums

**Comment by donskov** [comment]
`@peculiar/asn1-lei` works for me
