### ISSUE TITLE
EnrollCertType parse error

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/asn1-schema#18]
```ts
AsnParser.parse(Convert.FromHex('1e0a00530075006200430041'), EnrollCertType);
```

![image](https://user-images.githubusercontent.com/9417251/83354931-ac3da680-a364-11ea-812b-6d2a57b1da36.png)

**Comment by microshine** [comment]
![image](https://user-images.githubusercontent.com/7333669/83399341-b796dd80-a409-11ea-820b-52ac5ba3e72f.png)
![image](https://user-images.githubusercontent.com/7333669/83399375-c41b3600-a409-11ea-9be1-13c42e2036ff.png)

**Comment by microshine** [comment]
Hm
![image](https://user-images.githubusercontent.com/7333669/83400091-f4af9f80-a40a-11ea-82aa-c065167b3e72.png)

**Comment by microshine** [comment]
Funny :)
https://github.com/freeipa/freeipa/blob/33f39d88bf0bb871e3868c827aeb335eb40f5ae3/ipalib/x509.py#L843-L847

**Comment by donskov** [comment]
Works for me. Thanks
