### ISSUE TITLE
CaVersion export missed

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/asn1-schema#22]
Missed export [CaVersion](https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509-microsoft/src/attributes/extensions/ca_version.ts) from the [package](https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509-microsoft/src/attributes/extensions/index.ts)

**Comment by microshine** [comment]
```
@peculiar/asn1-x509-microsoft@2.0.6
```
