### ISSUE TITLE
Android KeyStore extension

### ISSUE THREAD

**Issue by MasterKale** [PeculiarVentures/asn1-schema#23]
I'm starting work on defining a schema for Android's Keystore extension as detailed here:

https://source.android.com/security/keystore/attestation#schema

Might there be interest in this extension being added to this library? I'm prepared to PR it in if that's the case.

**Comment by rmhrisk** [comment]
This totally sounds useful and an appropriate thing for this library. We would be happy to help with any questions. @microshine is king on this project.

**Comment by MasterKale** [comment]
Speaking of questions, perhaps you can help me make sense of how I should define a couple of sections of the schema. I will preface my question with the fact that I'm very new to the world of ASN.1 parsing. Before I found this library I'd written a parser to output a crude JSON data structure I then traversed down into by array index until I got to the values I needed. This library offers a much cleaner way to parse these things, though, and after simplifying a lot of existing code thanks to the included x.509 schema I'm committed to replacing my brute-force ASN.1 parsing functions with your library.

That said, here's a document from a KeyStore attestation:

```
3081cf0201020a01000201010a010004209f54497cde948349eae4f48de970808d4ddcdce4ddeee23b76d5c5ddcc1b898e04003069bf853d080206015ed3e3cfa0bf85455904573055312f302d0428636f6d2e616e64726f69642e6b657973746f72652e616e64726f69646b657973746f726564656d6f0201013122042074cfcb507488f529108591c7a505919f327732fbc1d803526aea980006d2d8983032a1053103020102a203020103a30402020100a5053103020104aa03020101bf837803020102bf853e03020100bf853f020500
```

Here's it rendered:
<img width="824" alt="Screen Shot 2020-07-09 at 4 47 58 PM" src="https://user-images.githubusercontent.com/5166470/87101479-123f0880-c204-11ea-9fea-09725cca76e5.png">

I'm having issues defining `AuthorizationList`, the type of the last two `SEQUENCE`'s in the structure. I've made it as far as parsing `purpose`:

```typescript
class AuthorizationList {
  @AsnProp({ type: AsnPropTypes.Integer, repeated: 'set', context: 1, optional: true })
  public purpose?: number[];

  @AsnProp({ type: AsnPropTypes.Any, optional: true })
  public algorithm?: OctetString;
}
```

Here's the document that gets parsed for that struct:

```
KeyDescription {
  attestationVersion: 2,
  attestationSecurityLevel: 0,
  keymasterVersion: 1,
  keymasterSecurityLevel: 0,
  attestationChallenge: OctetString [ArrayBuffer] {
    [Uint8Contents]: <9f 54 49 7c de 94 83 49 ea e4 f4 8d e9 70 80 8d 4d dc dc e4 dd ee e2 3b 76 d5 c5 dd cc 1b 89 8e>,
    byteLength: 32
  },
  uniqueId: OctetString [ArrayBuffer] { [Uint8Contents]: <>, byteLength: 0 },
  softwareEnforced: AuthorizationList {
    algorithm: OctetString [ArrayBuffer] {
      [Uint8Contents]: <bf 85 3d 08 02 06 01 5e d3 e3 cf a0>,
      byteLength: 12
    }
  },
  teeEnforced: AuthorizationList {
    purpose: [ 2 ],
    algorithm: OctetString [ArrayBuffer] {
      [Uint8Contents]: <a2 03 02 01 03>,
      byteLength: 5
    }
  }
}
```

(I know `algorithm` is wrong, but without it the parser fails with "Data does not match to AuthorizationList ASN1 schema.")

How should I define the items in `softwareEnforced` and `teeEnforced` that have a type of `[number]`?

For reference, here's the first few definitions of `AuthorizationList` schema:

```
AuthorizationList ::= SEQUENCE {
  purpose                     [1] EXPLICIT SET OF INTEGER OPTIONAL,
  algorithm                   [2] EXPLICIT INTEGER OPTIONAL,
  keySize                     [3] EXPLICIT INTEGER OPTIONAL.
  digest                      [5] EXPLICIT SET OF INTEGER OPTIONAL,
  padding                     [6] EXPLICIT SET OF INTEGER OPTIONAL,
  ...
```

Thanks for your help pushing past this.

**Comment by microshine** [comment]
@MasterKale I've added and published `@peculiar/asn1-android@2.0.7-alpha.0` module. Please try it. Let me know if everything is ok then I'll publish a new version.

### Install alpha version
```
npm i @peculiar/asn1-schema @peculiar/asn1-android@2.0.7-alpha.0
```

### Example
```js
const { AsnConvert } = require("@peculiar/asn1-schema");
const { KeyDescription } = require("@peculiar/asn1-android");

const hex = "3081cf0201020a01000201010a010004209f54497cde948349eae4f48de970808d4ddcdce4ddeee23b76d5c5ddcc1b898e04003069bf853d080206015ed3e3cfa0bf85455904573055312f302d0428636f6d2e616e64726f69642e6b657973746f72652e616e64726f69646b657973746f726564656d6f0201013122042074cfcb507488f529108591c7a505919f327732fbc1d803526aea980006d2d8983032a1053103020102a203020103a30402020100a5053103020104aa03020101bf837803020102bf853e03020100bf853f020500";

const kd = AsnConvert.parse(Buffer.from(hex, "hex"), KeyDescription);
console.log(kd);

```

### Output
```js
KeyDescription {
  attestationVersion: 2,
  attestationSecurityLevel: 0,
  keymasterVersion: 1,
  keymasterSecurityLevel: 0,
  attestationChallenge: OctetString [ArrayBuffer] {
    [Uint8Contents]: <9f 54 49 7c de 94 83 49 ea e4 f4 8d e9 70 80 8d 4d dc dc e4 dd ee e2 3b 76 d5 c5 dd cc 1b 89 8e>,
    byteLength: 32
  },
  uniqueId: OctetString [ArrayBuffer] { [Uint8Contents]: <>, byteLength: 0 },
  softwareEnforced: AuthorizationList {
    creationDateTime: '1506793476000',
    attestationApplicationId: OctetString [ArrayBuffer] {
      [Uint8Contents]: <30 55 31 2f 30 2d 04 28 63 6f 6d 2e 61 6e 64 72 6f 69 64 2e 6b 65 79 73 74 6f 72 65 2e 61 6e 64 72 6f 69 64 6b 65 79 73 74 6f 72 65 64 65 6d 6f 02 01 01 31 22 04 20 74 cf cb 50 74 88 f5 29 10 85 91 c7 a5 05 91 9f 32 77 32 fb c1 d8 03 52 6a ea 98 00 06 d2 d8 98>,
      byteLength: 87
    }
  },
  teeEnforced: AuthorizationList {
    purpose: IntegerSet(1) [ 2 ],
    algorithm: 3,
    keySize: 256,
    digest: IntegerSet(1) [ 4 ],
    ecCurve: 1,
    userAuthType: 2,
    origin: 0,
    rollbackResistant: null
  }
}
```

**Comment by MasterKale** [comment]
This worked beautifully, thank you!

I see I was on the right track about using `context`, so I feel a bit better about my efforts. I'm curious, though, if the trick in making AuthorizationList work was this bit where you defined `Partial<AuthorizationList>` in the `constructor()`:

 ```
public constructor(params: Partial<AuthorizationList> = {}) {
    Object.assign(this, params);
  }
```

Was this because almost everything in AuthorizationList was marked `OPTIONAL` in the schema? I'm taking notes for the next time I might need to define a schema :)

**Comment by MasterKale** [comment]
And before you cut a new release, I'd like to recommend changing instances of "Android key" to "Android KeyStore", especially in this new package's README.md. It'll make it way easier for future developers to find this new package because "KeyStore" differentiates this type of attestation schema from existing Android schemas, like SafetyNet, and whatever else Google will come out with in the future.

**Comment by rmhrisk** [comment]
@MasterKale please do PR to provide any appropriate rename and documentation

**Comment by MasterKale** [comment]
I'm going to close this out for now since the package is now published, and works great to boot! Thank you again 😄
