### ISSUE TITLE
Testing with Jest

### ISSUE THREAD

**Issue by bokunobaka** [PeculiarVentures/asn1-schema#32]
So I have been using this library to serialize and deserialize ASN1 structures and wanted writes tests for the code.
I've been having trouble getting the frameworks running. I would really appreciate if you could give me some pointers.

I'm writing it in TypeScript and wanted to test out Jest, but I run into the following error when running Jest:
![image](https://user-images.githubusercontent.com/60262412/91037740-35861180-e612-11ea-8ad6-444bc140de68.png)

From what i understand the type for data in AsnParse.parse is BufferSource that is either ArrayBuffer or ArrayBufferView, Base64.decode returns ArrayBuffer, so everything should be fine, but I can't get past this error.

TypeScript itself compiles and I can use the built library and the same method without any errors.

Any suggestions?

**Comment by microshine** [comment]
Are you sure that your Base64 class returns `ArrayBuffer`? Please log your `Base64.decode` result.

If it's a number `Array` put it to `Uint8Array`

```js
const spki = new Uint8Array(Base64.decode(Base64.unarmor(input)));
```

**Comment by bokunobaka** [comment]
![image](https://user-images.githubusercontent.com/60262412/91042904-3b342500-e61b-11ea-8abc-8e0fd1e94db9.png)

![image](https://user-images.githubusercontent.com/60262412/91042956-52731280-e61b-11ea-8b52-db1474df48e9.png)

**Comment by microshine** [comment]
It's interesting. Incomming parameter doesn't match to this condition.
```js
let buf;
if (data instanceof ArrayBuffer) {
    buf = data;
}
else if (typeof Buffer !== "undefined" && Buffer.isBuffer(data)) {
    buf = new Uint8Array(data).buffer;
}
else if (ArrayBuffer.isView(data) || data.buffer instanceof ArrayBuffer) {
    buf = data.buffer;
}
else {
    throw new TypeError("Wrong type of 'data' argument");
}
```

**Comment by bokunobaka** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array
**Uint8Array.prototype.buffer**
    Returns the ArrayBuffer referenced by the Uint8Array Fixed at construction time and thus read only.

This so the output of the Base64.decode should be of ArrayBuffer, but for some reason it's seen as _object_:
![image](https://user-images.githubusercontent.com/60262412/91043656-a7635880-e61c-11ea-934e-37b618cb0780.png)
![image](https://user-images.githubusercontent.com/60262412/91043678-afbb9380-e61c-11ea-8e39-af1137492e27.png)

**Comment by microshine** [comment]
> The funny thing is that this only happens if I use "jest", using "tsc" to compile and using the compiled library in an Angular application it works correctly.

Maybe `jest` does something with `ArrayBuffer` or `Uint8Array` and they are not the same

**Comment by microshine** [comment]
I'll try to reproduce that error

**Comment by bokunobaka** [comment]
> It's interesting. Incomming parameter doesn't match to this condition.
> 
> ```js
> let buf;
> if (data instanceof ArrayBuffer) {
>     buf = data;
> }
> else if (typeof Buffer !== "undefined" && Buffer.isBuffer(data)) {
>     buf = new Uint8Array(data).buffer;
> }
> else if (ArrayBuffer.isView(data) || data.buffer instanceof ArrayBuffer) {
>     buf = data.buffer;
> }
> else {
>     throw new TypeError("Wrong type of 'data' argument");
> }
> ```
Also what I noticed now is that when i try to pass in the Uint8Array version of the ArrayBuffer the browser runs into the error: 
**"ERROR ReferenceError: Buffer is not defined"**
This probably comes from the fact that I'm running it on browser and Buffer comes from node if I am correct. Which is why I am using the ArrayBuffer as the input.

Thank you very much for the help.

**Comment by microshine** [comment]
> "ERROR ReferenceError: Buffer is not defined"

It works fine in Chrome

![image](https://user-images.githubusercontent.com/7333669/91045956-5190af80-e620-11ea-97b8-7ff3e792bfbc.png)

**Comment by bokunobaka** [comment]
> > "ERROR ReferenceError: Buffer is not defined"
> 
> It works fine in Chrome
> 
> ![image](https://user-images.githubusercontent.com/7333669/91045956-5190af80-e620-11ea-97b8-7ff3e792bfbc.png)

Then that is most probably because of the compiler options.

**Comment by microshine** [comment]
Just for experiment. Try to use `pvtsutils`. It has `Convert` class which supports `utf8`, `hex`, `base64`, `base64url`, and it works in browser.

https://github.com/PeculiarVentures/pvtsutils/blob/master/src/convert.ts

**Comment by bokunobaka** [comment]
Tried it,
same result: tsc works, using the compiled library works, jest throws error:
"TypeError: Wrong type of 'data' argument"

**Comment by bokunobaka** [comment]
Figured it out with the help of this:
[https://github.com/facebook/jest/issues/7780#issuecomment-669828353](https://github.com/facebook/jest/issues/7780#issuecomment-669828353)

It seems that the latest jest-environment-jsdom@26 is to blame. When I changed to the previous version jest-environment-jsdom@25 everything works.

`npm install jest-environment-jsdom@25`

If it's fine with you we can close this issue now.

**Comment by microshine** [comment]
@bokunobaka Thank you!
