### ISSUE TITLE
Error trying to parse PolicyMappings extension

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/asn1-schema#68]
Code example:
```ts
AsnParser.parse(Convert.FromHex('304e3018060a60864801650302010302060a608648016503020102073018060a60864801650302010303060a608648016503020102083018060a6086480165030201030c060a60864801650302010209'), PolicyMappings);
```

Error text: 
```
Data does not match to PolicyMappings ASN1 schema.
```

PolicyMappings extension reference - https://lapo.it/asn1js/#ME4wGAYKYIZIAWUDAgEDAgYKYIZIAWUDAgECBzAYBgpghkgBZQMCAQMDBgpghkgBZQMCAQIIMBgGCmCGSAFlAwIBAwwGCmCGSAFlAwIBAgk

**Comment by microshine** [comment]
Current version implements PolicyMappings as a single SEQUENCE. But it must be a SEQUENCE of SEQUENCE.

Fixing it

**Comment by microshine** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/7333669/163561008-102a122b-d4df-4137-b8a8-b6e727821199.png">

**Comment by microshine** [comment]
`@peculiar/asn1-x509@2.1.4` has been published
