### ISSUE TITLE
Ambiguity around intended runtime environment of these packages

### ISSUE THREAD

**Issue by MasterKale** [PeculiarVentures/asn1-schema#70]
I'm using several of your excellent schemas in a Typescript-authored node library, which to date have seemingly worked fine. Here's how I declare them in my library's **package.json** list of `"dependencies"`:

```
"@peculiar/asn1-android": "^2.0.38",
"@peculiar/asn1-schema": "^2.0.38",
"@peculiar/asn1-x509": "^2.0.38",
```

Unfortunately recently my builds are failing in CI with the following type errors:

```
node_modules/asn1js/build/index.d.ts:117:25 - error TS2304: Cannot find name 'BufferSource'.

117     valueBeforeDecode?: BufferSource;
                            ~~~~~~~~~~~~

node_modules/asn1js/build/index.d.ts:167:15 - error TS2304: Cannot find name 'BufferSource'.

167     valueHex: BufferSource;
                  ~~~~~~~~~~~~

node_modules/asn1js/build/index.d.ts:1323:39 - error TS2304: Cannot find name 'BufferSource'.

1323 declare function fromBER(inputBuffer: BufferSource): FromBerResult;
                                           ~~~~~~~~~~~~

node_modules/asn1js/build/index.d.ts:1354:44 - error TS2304: Cannot find name 'BufferSource'.

1354 declare function verifySchema(inputBuffer: BufferSource, inputSchema: AsnSchemaType): CompareSchemaResult;
                                                ~~~~~~~~~~~~
```

Doing some digging, at some point since v2.0.38 of the three schema libs above, asn1js started referencing types which are only defined in TypeScript's `"DOM"` lib. And indeed, adding the following to my Node library's **tsconfig.json** fixed these errors:

```
"lib": [
  "DOM",
],
```

I no longer reference `"DOM"` in my library's **tsconfig.json** because my library is only intended to work in Node; and in fact referencing `"DOM"` like this can lead to typing issues with things like (for sake of example) `setTimeout()` because its return types between Node and browser environments are slightly different.

So that brings me to my question: **are these libraries only intended to be used in a browser?** I ask because asn1js underpins the functionality of these schema libraries, and states the following:

> [ASN1js](http://asn1js.org/) is the first library for [BER](http://en.wikipedia.org/wiki/X.690#BER_encoding) encoding/decoding in Javascript designed for browser use.

Does that mean these schema libraries should never have been used in my Node library in the first place? I've not yet had any issues using them like this, but if asn1js's types are going to assume the code is running in a DOM then it's making me wonder if I should reconsider and find an alternative.

If these schema libraries are also intended for use in Node, then the type definitions in asn1js need further consideration to help ensure Node-based TypeScript projects can reference the proper types without needing to reference the likely irrelevant TypeScript `"DOM"` lib.

If these schema libraries are only intended for use in browsers then I think `asn1-schema` could benefit from clearer messaging specifying this expected runtime environment restriction.

**Comment by MasterKale** [comment]
BTW here are some package versions I'm seeing in **node_modules/** tonight on a fresh `npm install` based on those three `"asn-"` packages defined above:

- `@peculiar/asn1-android@2.1.6`
- `@peculiar/asn1-schema@2.1.6`
- `@peculiar/asn1-x509@2.1.6`
- `asn1js@3.0.2`

One nuance to all of this is that I don't ship package-lock.json's with my libraries, so consumers (and CI) can pick up the latest versions of my library's dependencies on every install. In this case it's causing unexpected CI failures despite no code changes after a previous successful CI run, because I waited three weeks between CI runs and these packages happened to get updated in that time. I think that means it's something that changed in asn1js between now and April 27?

**Comment by microshine** [comment]
I've updated and published all `@peculiar/asn1` packages. Now it uses `ES2019` lib and `BufferSource` from `pvtsutils` module.

Please try the new version.

```
Successfully published:
 - @peculiar/asn1-adobe-acrobat@2.1.7
 - @peculiar/asn1-android@2.1.7
 - @peculiar/asn1-cert-transparency@2.1.7
 - @peculiar/asn1-cms@2.1.7
 - @peculiar/asn1-csr@2.1.7
 - @peculiar/asn1-ecc@2.1.7
 - @peculiar/asn1-ess@2.1.7
 - @peculiar/asn1-lei@2.1.7
 - @peculiar/asn1-ntqwac@2.1.7
 - @peculiar/asn1-ocsp@2.1.7
 - @peculiar/asn1-pfx@2.1.7
 - @peculiar/asn1-pkcs8@2.1.7
 - @peculiar/asn1-pkcs9@2.1.7
 - @peculiar/asn1-rfc8226@2.1.7
 - @peculiar/asn1-rsa@2.1.7
 - @peculiar/asn1-schema@2.1.7
 - @peculiar/asn1-tsp@2.1.7
 - @peculiar/asn1-x509-attr@2.1.7
 - @peculiar/asn1-x509-logotype@2.1.7
 - @peculiar/asn1-x509-microsoft@2.1.7
 - @peculiar/asn1-x509-netscape@2.1.7
 - @peculiar/asn1-x509-qualified-etsi@2.1.7
 - @peculiar/asn1-x509-qualified@2.1.7
 - @peculiar/asn1-x509-trustanchor@2.1.7
 - @peculiar/asn1-x509@2.1.7
```

**Comment by MasterKale** [comment]
I forgot to follow up, thank you very much @microshine for such a speedy response and resolution. I'm happy to report that 2.1.7 fixed the problem 😌
