### ISSUE TITLE
Decode Integer 4 bytes value to zero

### ISSUE THREAD

**Issue by oleggrib** [PeculiarVentures/asn1-schema#75]
Hi.
I found out an issue when 4 bytes Integer always decodes to 0. 
Problem because of inconsistency of asn1js and asn1-schama

asn1js: https://github.com/PeculiarVentures/ASN1.js/blob/master/src/internals/LocalIntegerValueBlock.ts#L135
```
export class LocalIntegerValueBlock extends HexBlock(ValueBlock) implements IDerConvertible {
  protected setValueHex(): void {
    if (this.valueHexView.length >= 4) {
      this.warnings.push("Too big Integer for decoding, hex only");
      this.isHexOnly = true;
      this._valueDec = 0;
    }
```

but asn1-schama: https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/schema/src/converters.ts#L31

```
export const AsnIntegerConverter: IAsnConverter<IntegerConverterType> = {
  fromASN: (value: any) => value.valueBlock.valueHex.byteLength > 4
    ? value.valueBlock.toString() // Convert number to string
    : value.valueBlock.valueDec, // use number format
  toASN: (value: IntegerConverterType) => new asn1.Integer({ value: value as any }),
};
```

please replace ```value.valueBlock.valueHex.byteLength > 4``` with ```value.valueBlock.valueHex.byteLength >= 4``` , it will solve the problem. @microshine

**Comment by oleggrib** [comment]
@microshine , could you please remove parseInt here:
https://github.com/PeculiarVentures/asn1-schema/blob/be0b98bd114dea4653e20ed660a0e830754ec9fc/packages/schema/src/converters.ts#L32

because it will break BigInt values. Thanks

**Comment by oleggrib** [comment]
@microshine , could you please remove parseInt here:
https://github.com/PeculiarVentures/asn1-schema/blob/be0b98bd114dea4653e20ed660a0e830754ec9fc/packages/schema/src/converters.ts#L32

because it will break BigInt values. Thanks

**Comment by microshine** [comment]
I think it's not good to use mixed type like it was before. This is why I updated it to number only type. Now default Integer converter returns number only. But I agree it's not good if you are using this value for BigInt creation.

I'm adding `AsnIntegerBigIntConverter` and going to publish it soon

Here is a test code with `AsnIntegerBigIntConverter` usage
```ts
@src.AsnChoiceType()
class Test {
  @src.AsnProp({ type: src.AsnPropTypes.Integer, converter: src.AsnIntegerBigIntConverter })
  public value!: bigint;
}

const value = BigInt("5172094299709469602635084381097487");

const test = new Test();
test.value = value;

const asn = src.AsnConvert.serialize(test);
assert.strictEqual(Buffer.from(asn).toString("hex"), "020f00ff010203040508090a0b0c0d0e0f");
```

@oleggrib do you have the problem with an existing ASN schema from `@peculiar` scope?

**Comment by oleggrib** [comment]
> @oleggrib do you have the problem with an existing ASN schema from @peculiar scope?

@microshine , I had problems, so I created patch and read values as number|string
I think you can return the value always as string and developer have to detect if its integer or bigint.

bigint can be popular enough nowadays mostly because or crypto-projects and string cover all cases.

**Comment by microshine** [comment]
I've published the new version. Now you can use `AsnIntegerBigIntConverter` or default converter which supports `string | number`

```
Successfully published:
 - @peculiar/asn1-adobe-acrobat@2.2.0
 - @peculiar/asn1-android@2.2.0
 - @peculiar/asn1-cert-transparency@2.2.0
 - @peculiar/asn1-cms@2.2.0
 - @peculiar/asn1-csr@2.2.0
 - @peculiar/asn1-ecc@2.2.0
 - @peculiar/asn1-ess@2.2.0
 - @peculiar/asn1-lei@2.2.0
 - @peculiar/asn1-ntqwac@2.2.0
 - @peculiar/asn1-ocsp@2.2.0
 - @peculiar/asn1-pfx@2.2.0
 - @peculiar/asn1-pkcs8@2.2.0
 - @peculiar/asn1-pkcs9@2.2.0
 - @peculiar/asn1-rfc8226@2.2.0
 - @peculiar/asn1-rsa@2.2.0
 - @peculiar/asn1-schema@2.2.0
 - @peculiar/asn1-tsp@2.2.0
 - @peculiar/asn1-x509-attr@2.2.0
 - @peculiar/asn1-x509-logotype@2.2.0
 - @peculiar/asn1-x509-microsoft@2.2.0
 - @peculiar/asn1-x509-netscape@2.2.0
 - @peculiar/asn1-x509-qualified-etsi@2.2.0
 - @peculiar/asn1-x509-qualified@2.2.0
 - @peculiar/asn1-x509-trustanchor@2.2.0
 - @peculiar/asn1-x509@2.2.0
```

See https://github.com/PeculiarVentures/asn1-schema/pull/77
