### ISSUE TITLE
Unexpected token causes build failure

### ISSUE THREAD

**Issue by zwfn88** [PeculiarVentures/asn1-schema#78]
https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509/src/extensions/crl_issuing_distribution_point.ts#L35

https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509/src/extensions/crl_issuing_distribution_point.ts#L38

https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509/src/extensions/crl_issuing_distribution_point.ts#L44

https://github.com/PeculiarVentures/asn1-schema/blob/master/packages/x509/src/extensions/crl_issuing_distribution_point.ts#L47

Extra ; causes build failure.

Unexpected token: punc (;) [./node_modules/@peculiar/asn1-x509/build/cjs/extensions/crl_issuing_distribution_point.js:19,0]

**Comment by rmhrisk** [comment]
Have you built the package?

**Comment by zwfn88** [comment]
Yes, the build failed in our prod pipeline.

**Comment by microshine** [comment]
I'll fix it soon. Going to add lint for this project

**Comment by microshine** [comment]
The new version `v2.3.0` has been published

@zwfn88 please try it
