### ISSUE TITLE
id_ct_tstInfo is not passed testing, + expected - actual  -1.2.840.113549.1.7.2 +1.2.840.113549.1.9.16.1.4

### ISSUE THREAD

**Issue by codewithmecoder** [PeculiarVentures/asn1-schema#89]
I have faced this problem for days I could not find any solution.
Any ideas?
Thanks

[GitHub repo]( https://github.com/codewithmecoder/tsp-testing/blob/main/src/test/index.ts)

+ actual - expected

+ '1.2.840.113549.1.7.2'
- '1.2.840.113549.1.9.16.1.4'
                    ^
      + expected - actual

      -1.2.840.113549.1.7.2
      +1.2.840.113549.1.9.16.1.4

      at C:\projects\tsr\src\test\index.ts:30:12
      at Generator.next (<anonymous>)
      at fulfilled (src\test\index.ts:28:58)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

If I comment `assert.strictEqual(contentInfo.contentType, id_ct_tstInfo);` out. 
It is giving me a new error: 

`TSP
    1) parse TSTInfo

  0 passing (870ms)
  1 failing

  1) TSP
       parse TSTInfo:
     TypeError: Argument 'asn' is not instance of ASN.1 OctetString
      at OctetString.fromASN (node_modules\@peculiar\asn1-schema\build\cjs\types\octet_string.js:31:19)
      at Function.fromASN (node_modules\@peculiar\asn1-schema\build\cjs\parser.js:24:30)
      at Function.parse (node_modules\@peculiar\asn1-schema\build\cjs\parser.js:16:26)
      at Function.parse (node_modules\@peculiar\asn1-schema\build\cjs\convert.js:13:35)
      at C:\projects\tsr\src\test\index.ts:36:32
      at Generator.next (<anonymous>)
      at fulfilled (src\test\index.ts:28:58)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by microshine** [comment]
`contentType` should be `id-signedData`. `contentInfo.content` keeps the content of `OCTET_STRING`

```js
const contentInfo = AsnConvert.parse(file, TimeStampToken);
assert.strictEqual(contentInfo.contentType, id_signedData);

const tstInfo = AsnConvert.parse(contentInfo.content, TSTInfo);
```

```asn
SEQUENCE (2 elem)
  OBJECT IDENTIFIER 1.2.840.113549.1.7.2 signedData (PKCS #7)
  [0] (1 elem)
    SEQUENCE (5 elem)
      INTEGER 3
      SET (1 elem)
        SEQUENCE (1 elem)
          OBJECT IDENTIFIER 2.16.840.1.101.3.4.2.1 sha-256 (NIST Algorithm)
      SEQUENCE (2 elem)
        OBJECT IDENTIFIER 1.2.840.113549.1.9.16.1.4 tSTInfo (S/MIME Content Types)
```

**Comment by codewithmecoder** [comment]
id_signedData and id_ct_tstInfo are the same. 
`contentInfo.contentType` the value was `1.2.840.113549.1.9.16.1.4` it's not `1.2.840.113549.1.7.2`.

**Comment by codewithmecoder** [comment]
That's what make the test failed

**Comment by microshine** [comment]
> id_signedData and id_ct_tstInfo are the same.

This is wrong. They are different

```asn
id-signedData OBJECT IDENTIFIER ::= { iso(1) member-body(2)
   us(840) rsadsi(113549) pkcs(1) pkcs7(7) 2 }

id-ct-TSTInfo  OBJECT IDENTIFIER ::= { iso(1) member-body(2)
   us(840) rsadsi(113549) pkcs(1) pkcs-9(9) smime(16) ct(1) 4}
```

**Comment by microshine** [comment]
Please look at this [TimeStamp ASN.1 structure](https://lapo.it/asn1js/#MIIU8wYJKoZIhvcNAQcCoIIU5DCCFOACAQMxDTALBglghkgBZQMEAgEwggFdBgsqhkiG9w0BCRABBKCCAUwEggFIMIIBRAIBAQYKKoF6AYExAgkBATAvMAsGCWCGSAFlAwQCAQQgQzzvcgIIVtKnBR7JyGuymfZVC4bU2YbLn1eVylEQ-1kCEQDvbA9Vj1NM-7anAOHyhImtGA8yMDIzMDEyMDAxMjg0MlowAwIBAQIkY2Y5YzM1MjctZTZiYi00ZGQ2LWI1ZjUtNzBiMWFmMzVjN2M3oIGVpIGSMIGPMQswCQYDVQQGEwJGUjESMBAGA1UECgwJREhJTVlPVElTMR0wGwYDVQRhDBROVFJGUi00ODE0NjMwODEwMDAzNjEcMBoGA1UECwwTMDAwMiA0ODE0NjMwODEwMDAzNjEaMBgGA1UEAwwRREhJTVlPVElTIC0gVFNVMTUxEzARBgNVBAUTClQyNDk5MjE4NDKhGzAZBggrBgEFBQcBAwQNMAswCQYHBACBl14BAaCCEQUwggOoMIICkKADAgECAgkA_tzjAQ_JSP8wDQYJKoZIhvcNAQEFBQAwNDELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURoaW15b3RpczERMA8GA1UEAwwIQ2VydGlnbmEwHhcNMDcwNjI5MTUxMzA1WhcNMjcwNjI5MTUxMzA1WjA0MQswCQYDVQQGEwJGUjESMBAGA1UECgwJRGhpbXlvdGlzMREwDwYDVQQDDAhDZXJ0aWduYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMho8cnW1rM0dSaCHuy0vupc4SbtEUdh4aJ8FnhAIeRgnlrIY-HEsZaS_xhtaSPhK2L33eI2L5EHuUjPDux5tiznNEtwCCWjPIcbGfKBBw84kBnTEf6GtPLRXh4els2AbM47MZO28qDQqZUSfaWazGvIhFaKM6nnIhVTFvDMF-xXX-miCpgJ3uNfnG_cSOOFCxVaprqfrEjjCbL39DLeXjS-HHhdQlvODiKPTZDXfTIYswssar-OPxQRiSAOdxS1PZQIh_clHtWyYADsbyooJW4qPhhjFyU_PkQgFvYmyCWuBUq052Ms84wWU35c-xEaCMFGYp8iuPHCjWnc-jpYBt8CAwEAAaOBvDCBuTAPBgNVHRMBAf8EBTADAQH_MB0GA1UdDgQWBBQa7f5BOZC0JFm-AfJS1UX2WjncETBkBgNVHSMEXTBbgBQa7f5BOZC0JFm-AfJS1UX2WjncEaE4pDYwNDELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURoaW15b3RpczERMA8GA1UEAwwIQ2VydGlnbmGCCQD-3OMBD8lI_zAOBgNVHQ8BAf8EBAMCAQYwEQYJYIZIAYb4QgEBBAQDAgAHMA0GCSqGSIb3DQEBBQUAA4IBAQCFAx6ScfZCr-GjYZ7r88AP8qXU2pXm1r5oNj1-bh9Miu_RDyFtXqVSY84S-O8q2m_rN_4TAsfLOz4ia9phLn_Ucj3dMOEeTEAZjA_XnNGDMHuYWdx9xrkMKUyhM6LrZzplhNOW4u12RXCPtSve-SPWSW48FLXGnzUeUNDBj2pwRAJiy64daEGnqlfoU6oH0gb21RQGC5EDdSxscrVhlZoNi7kN5_XfVM3e5tjWCQiXY-XBLrC3RCbAJsCvVTCeO9U2KhkE9Fwe_88st__Q_YdAEdURI7tIwCGppCgt_RX4sE4r9DBbIfwRkTS-Qe97nZd1_5eVwJZYL-q7Rte75NkuMIIGFTCCBP2gAwIBAgIRAPlPiLTzBzmpCdNvjtZMWaYwDQYJKoZIhvcNAQELBQAwNDELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURoaW15b3RpczERMA8GA1UEAwwIQ2VydGlnbmEwHhcNMTUxMTI1MTAyNDA3WhcNMjUxMTIyMTAyNDA3WjB7MQswCQYDVQQGEwJGUjESMBAGA1UECgwJREhJTVlPVElTMRwwGgYDVQQLDBMwMDAyIDQ4MTQ2MzA4MTAwMDM2MR0wGwYDVQRhDBROVFJGUi00ODE0NjMwODEwMDAzNjEbMBkGA1UEAwwSQ2VydGlnbmEgRW50aXR5IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0lTrAwYaOJpvbeSPdj8l4DVUCP2td5ZpJ6YBETkj0DEyairmzh-QdoqJusE0bPu7DeivGYLaIfZP53fVi-OM8_TfiQK61B53kgwI1tL1nEhdLd7G8G7SrKs0HGSofk6KMWqn4t2kVkkvotuH5RzxW_TrYyF9kUrBvqcAqUigpPtNv2w6JRmEN3QpYYDjG4Bwz4J3RMRMtq5z6T1F55hX1hFP7FcavN-q4GiJ6m7LMhwiwh7nHU71lmLhUrYHAIrygN_eQobCnV8HiSxBm0eFtnJDXWUd7KdkdJ02E67aclV625Vwzw-0OKH20XBqO4tO8Yy0TuJnZQGfA_tSxdfp7hxNWlXFHvkaRGTfj9y6tv9WVZrgcNbaXR4c3gjE_GuhGDCqt32ogTKu37cHMBxCRXCgMWEAyz4tBDVT8_UZzDbyFJOe63aroZdoohI4XkEj50fYT6-AoEl0UoctswbPzq1PdIzXb-u8ki4FZK_2sTwCKJxifplzj9eFcv0mcEVyYozVPAPzAo1aksK1_KWSCdHB2Odo5dhLlyiG_AmVcdA7NlQEPg6fSkJcbZV5kNnmkI9bgQv0iVFO9y0s1AlzfFcIrFCLS_A1UsL6-59H1ifSubehmD4ms8At83_NjyAjEJCs7UvIGkSFe54ifSnIdB03KZaz6cnFIwPy7ThPU4kCAwEAAaOCAdkwggHVMBIGA1UdEwEB_wQIMAYBAf8CAQAwDgYDVR0PAQH_BAQDAgEGMB0GA1UdDgQWBBSlPx4kTGz4i9IbcphGUMrohlW52DBkBgNVHSMEXTBbgBQa7f5BOZC0JFm-AfJS1UX2WjncEaE4pDYwNDELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURoaW15b3RpczERMA8GA1UEAwwIQ2VydGlnbmGCCQD-3OMBD8lI_zBJBgNVHSAEQjBAMD4GCiqBegGBMQEAAQIwMDAuBggrBgEFBQcCARYiaHR0cHM6Ly93d3cuY2VydGlnbmEuZnIvYXV0b3JpdGVzLzB8BggrBgEFBQcBAQRwMG4wNAYIKwYBBQUHMAKGKGh0dHA6Ly9hdXRvcml0ZS5jZXJ0aWduYS5mci9jZXJ0aWduYS5kZXIwNgYIKwYBBQUHMAKGKmh0dHA6Ly9hdXRvcml0ZS5kaGlteW90aXMuY29tL2NlcnRpZ25hLmRlcjBhBgNVHR8EWjBYMCmgJ6AlhiNodHRwOi8vY3JsLmNlcnRpZ25hLmZyL2NlcnRpZ25hLmNybDAroCmgJ4YlaHR0cDovL2NybC5kaGlteW90aXMuY29tL2NlcnRpZ25hLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAq05OtV0WmCyLpzxxcw98xPV8OiY56TQch4KEGotY1Dfw7H0nM7lap_6kAZkUwfI4WJt4piRedJHgasQOj-aJbpxCYX7Hv7vCnGDKZFC6c_vY3B_stbQRGTl__7-iKB2fgB_FoQOohrZqO77C0tqp1KuTfCSq_XAyZNtXoVn-YDaILMUHp2vslSHh131XPGjkloeXTMLf_-RcVVimMyAUjwdfcIUQEGU4Z5suQNWiwCU89l1UY7qaWC9As_GqWo3vqQG9ALG-HBFBr1HSPnUjW88J6CYUVxOcTDfAj3eJtvUF_3dFjPl6jM4rAJNeg-LqU6kQ-z_50yhrdgJ_A8cZiTCCBzwwggUkoAMCAQICEDwj1s1A7GzuZ2AiTy_JQh0wDQYJKoZIhvcNAQELBQAwezELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURISU1ZT1RJUzEcMBoGA1UECwwTMDAwMiA0ODE0NjMwODEwMDAzNjEdMBsGA1UEYQwUTlRSRlItNDgxNDYzMDgxMDAwMzYxGzAZBgNVBAMMEkNlcnRpZ25hIEVudGl0eSBDQTAeFw0yMjExMDIyMzAwMDBaFw0yNTExMDEyMjU5NTlaMIGPMQswCQYDVQQGEwJGUjESMBAGA1UECgwJREhJTVlPVElTMR0wGwYDVQRhDBROVFJGUi00ODE0NjMwODEwMDAzNjEcMBoGA1UECwwTMDAwMiA0ODE0NjMwODEwMDAzNjEaMBgGA1UEAwwRREhJTVlPVElTIC0gVFNVMTUxEzARBgNVBAUTClQyNDk5MjE4NDIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZLooVYA1_YlnziNtmvdwT-briXHI6Yrv1OKEsHS78zdEUw7Fd8POB1ddD_cREaPLlN7u0MsKZstpoEQJ3KyONyOrNqPzetThaFi9F-7_K5KA-CBlkv8asRc54HCt-wGYYFVBrDlyr2N5zZoKeqA52PINahiBm_qd7zzwjvhDsBqwtJhvQ9dfnGm6lmT2q-9mKDThsP927_TlUzwfysxT4JwmIuk_Nm_f_P_E4PP-OrxzvhjGyzx3MXFdjAY8qtUvqxq8ToQ3IAz2sPilQCyRWQGVU2tcL-LreRltCRJ1wfEmNQAdafXYyRglGqCp4P3Zb-HXuQ7W9jSx7znxdMeDBAgMBAAGjggKlMIICoTCB3AYIKwYBBQUHAQEEgc8wgcwwNgYIKwYBBQUHMAKGKmh0dHA6Ly9hdXRvcml0ZS5kaGlteW90aXMuY29tL2VudGl0eWNhLmRlcjA0BggrBgEFBQcwAoYoaHR0cDovL2F1dG9yaXRlLmNlcnRpZ25hLmZyL2VudGl0eWNhLmRlcjAuBggrBgEFBQcwAYYiaHR0cDovL2VudGl0eWNhLm9jc3AuZGhpbXlvdGlzLmNvbTAsBggrBgEFBQcwAYYgaHR0cDovL2VudGl0eWNhLm9jc3AuY2VydGlnbmEuZnIwHwYDVR0jBBgwFoAUpT8eJExs-IvSG3KYRlDK6IZVudgwCQYDVR0TBAIwADBXBgNVHSAEUDBOMEwGCyqBegGBMQIGAQkBMD0wOwYIKwYBBQUHAgEWL2h0dHBzOi8vd3d3LmNlcnRpZ25hLmNvbS9hdXRvcml0ZS1jZXJ0aWZpY2F0aW9uMGEGA1UdHwRaMFgwK6ApoCeGJWh0dHA6Ly9jcmwuZGhpbXlvdGlzLmNvbS9lbnRpdHljYS5jcmwwKaAnoCWGI2h0dHA6Ly9jcmwuY2VydGlnbmEuZnIvZW50aXR5Y2EuY3JsMBYGA1UdJQEB_wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB_wQEAwIGwDCBkAYIKwYBBQUHAQMEgYMwgYAwCAYGBACORgEBMF8GBgQAjkYBBTBVMCoWJGh0dHBzOi8vd3d3LmNlcnRpZ25hLmZyL2VuL2F1dG9yaXRlcxMCZW4wJxYhaHR0cHM6Ly93d3cuY2VydGlnbmEuZnIvYXV0b3JpdGVzEwJmcjATBgYEAI5GAQYwCQYHBACORgEGAjAdBgNVHQ4EFgQUAaRBoI830cuZNAlKoF3oefd_9yswDQYJKoZIhvcNAQELBQADggIBAK9nzH7nRfhN30IqE0ze_zERaGvlow0tP0fusbG9-I_iOsu1fE3jT7jPE7IL-_KAbHu3XxHkVHRMefwaXlHxtuU2jqcgSsMujSj4cW2YzR5P1LXtNtYBuBF68frRCZciKT9MygIAPIoai4NtXUGMjEfMsH0GaHM6kUorknw9DQtuy2xrbPoD9_HxFmOAYR9yul5TH4YJ_-Kwv6y4UHX3gxPgpe6dU4TlPQ2ots-gJOzrvowvlr73lgTs-RtxYeCCUyMTQPKZHIaWUq8P7O4Fv3mpnMc2WPcg8CjGw-h9V2xR-RiuDFhdDb2f_M78AEkP1NFsOeGTkeBtqIs7YQkfTKjSMgOIP69hqsajS68KofiBC7mbEwwcVhT09qY30bFEnmsKbcpgQkzvTqbVP6Dcf6gLZZTcr0mz_iy5hxKrhfzuF3t-TqclvJOUXmLoLMJDDHo0EyAoEJE29RS-tOO0ypYQW37kTHqXSw90LaGyo5Hgy0GF0QZq9wT37V12H4uGnYKjHLP_efHv59xgwzQGPK3ao7mqy3IlMUVCw6kjhZ9YDGbdTy8CSz1hzQ5CnrARaAy__SEARt0zR0wpEfYqFSAoCdG6vpyBdpbYEU92hbfXeRA507hxaJ7tgl3zbqQqQSlRlq66yYSbH38SuZi9RmZurfwy25O_79oBmDPJ25NwMYICYDCCAlwCAQEwgY8wezELMAkGA1UEBhMCRlIxEjAQBgNVBAoMCURISU1ZT1RJUzEcMBoGA1UECwwTMDAwMiA0ODE0NjMwODEwMDAzNjEdMBsGA1UEYQwUTlRSRlItNDgxNDYzMDgxMDAwMzYxGzAZBgNVBAMMEkNlcnRpZ25hIEVudGl0eSBDQQIQPCPWzUDsbO5nYCJPL8lCHTALBglghkgBZQMEAgGggaQwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0yMzAxMjAwMTI4NDJaMC8GCSqGSIb3DQEJBDEiBCBy1y3sDB2RncqArS_Qtuir7DY8oj9xYkCOE0XxDkhSQzA3BgsqhkiG9w0BCRACLzEoMCYwJDAiBCAJ-M5EbsKzSCCur5o5JJ_GdnpWHhgZa8xOTVowYSNnRDANBgkqhkiG9w0BAQsFAASCAQCdji9h38005_AQhne612V9gCbuhwyQ9UCPysKI0r26fVV5x6PFQDApqzU6gWrTJTaJDfop48s3kTpP-04H6dpE-dbhLnWVIHv4rB8PmUFoGN7opMZmnxIoT2M8bzuWrmXl0A-DucFcRZiqO9wXA36MHB_-hboOFbPWcrU1wafFxvrhAG_T5Vawlhfj4dK9FWCRqS4-V1sXj8ZZsOv_d2CkKEV-06aegOoscN5nHvU0kZ7sGjwk2O4SUFnHoMzGoHtv8AvIqEWLVgQ4Tff-j0ZZVQmqTaxpPfkrplFZ78XYDXfo3tPhaFAbRXnr5OzF9gcoedRFWGnJtZ3YPB13QlAj)

**Comment by codewithmecoder** [comment]
Here is my update code.
```ts
import { AsnConvert, AsnParser, OctetString } from "@peculiar/asn1-schema";
import * as assert from "assert";
import path from "path";
import fs from "fs/promises";
import { TimeStampToken, TSTInfo } from "@peculiar/asn1-tsp";
import { id_signedData } from "@peculiar/asn1-cms";
context("TSP", () => {
  it("parse TSTInfo", async () => {
    const file = await fs.readFile(
      path.join(__dirname, "../resoures/response.tsr")
    );
    const contentInfo = AsnParser.parse(file, TimeStampToken);
    console.log(contentInfo.contentType);
    assert.strictEqual(contentInfo.contentType, id_signedData);
    const tstInfo = AsnConvert.parse(contentInfo.content, TSTInfo);
    console.log(tstInfo);
  });
});
```

And got this error.
![2023-03-15_08h59_02](https://user-images.githubusercontent.com/69508607/225185002-8b504d7e-3804-42ad-a519-d78ac8639284.png)
